# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

    # Python formatter: black
-   repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3
